openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /api/leaderboard/{difficulty}:
    get:
      summary: 排行存档：获取无限榜
      deprecated: false
      description: 获取用户排行榜（三种榜单）
      operationId: api_get_leaderboard_api_leaderboard__difficulty__get
      tags:
        - api/leaderboard
      parameters:
        - name: cw_lb_token
          in: cookie
          description: 用户ID
          required: false
          example: LVoJxxEZVc2ujgJe93yMV3EtmoI5jmEiHTFIzzdj1mE
          schema:
            type: string
        - name: difficulty
          in: path
          description: ''
          required: true
          example: ''
          schema:
            type: string
            title: Difficulty
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                  status:
                    type: string
                    title: 请求状态
                  difficulty:
                    type: string
                    title: 难度水平
                  wins:
                    type: array
                    items:
                      type: object
                      properties:
                        rank:
                          type: integer
                        userId:
                          type: string
                        username:
                          type: string
                        ipLocation:
                          type: string
                        value:
                          type: integer
                        totalGames:
                          type: integer
                        wonGames:
                          type: integer
                        winRate:
                          type: number
                        avgRounds:
                          type: integer
                      x-apifox-orders:
                        - rank
                        - userId
                        - username
                        - ipLocation
                        - value
                        - totalGames
                        - wonGames
                        - winRate
                        - avgRounds
                    title: 胜利榜
                    nullable: true
                  winRate:
                    type: array
                    items:
                      type: object
                      properties:
                        rank:
                          type: integer
                        userId:
                          type: string
                        username:
                          type: string
                        ipLocation:
                          type: string
                        value:
                          type: number
                        totalGames:
                          type: integer
                        wonGames:
                          type: integer
                        winRate:
                          type: number
                        avgRounds:
                          type: integer
                      x-apifox-orders:
                        - rank
                        - userId
                        - username
                        - ipLocation
                        - value
                        - totalGames
                        - wonGames
                        - winRate
                        - avgRounds
                    title: 胜率榜
                    nullable: true
                  avgRounds:
                    type: array
                    items:
                      type: object
                      properties:
                        rank:
                          type: integer
                        userId:
                          type: string
                        username:
                          type: string
                        ipLocation:
                          type: string
                        value:
                          type: integer
                        totalGames:
                          type: integer
                        wonGames:
                          type: integer
                        winRate:
                          type: number
                        avgRounds:
                          type: integer
                      x-apifox-orders:
                        - rank
                        - userId
                        - username
                        - ipLocation
                        - value
                        - totalGames
                        - wonGames
                        - winRate
                        - avgRounds
                    title: 平均轮次榜
                    nullable: true
                  myRank:
                    type: object
                    properties:
                      wins:
                        type: integer
                      winRate:
                        type: integer
                      avgRounds:
                        type: integer
                    x-apifox-orders:
                      - wins
                      - winRate
                      - avgRounds
                    title: 我的排行
                    required:
                      - wins
                      - winRate
                      - avgRounds
                    nullable: true
                  myProfile:
                    type: object
                    properties:
                      id:
                        type: integer
                      userId:
                        type: string
                      username:
                        type: string
                      cookieToken:
                        type: string
                      ipLocation:
                        type: string
                      createTime:
                        type: string
                      updateTime:
                        type: string
                      easyTotal:
                        type: integer
                      easyWon:
                        type: integer
                      easyWinRounds:
                        type: integer
                      mediumTotal:
                        type: integer
                      mediumWon:
                        type: integer
                      mediumWinRounds:
                        type: integer
                      hardTotal:
                        type: integer
                      hardWon:
                        type: integer
                      hardWinRounds:
                        type: integer
                      easyWinRate:
                        type: integer
                      easyAvgRounds:
                        type: integer
                      mediumWinRate:
                        type: number
                      mediumAvgRounds:
                        type: integer
                      hardWinRate:
                        type: integer
                      hardAvgRounds:
                        type: integer
                    x-apifox-orders:
                      - id
                      - userId
                      - username
                      - cookieToken
                      - ipLocation
                      - createTime
                      - updateTime
                      - easyTotal
                      - easyWon
                      - easyWinRounds
                      - mediumTotal
                      - mediumWon
                      - mediumWinRounds
                      - hardTotal
                      - hardWon
                      - hardWinRounds
                      - easyWinRate
                      - easyAvgRounds
                      - mediumWinRate
                      - mediumAvgRounds
                      - hardWinRate
                      - hardAvgRounds
                    title: 我的信息
                    required:
                      - id
                      - userId
                      - username
                      - cookieToken
                      - ipLocation
                      - createTime
                      - updateTime
                      - easyTotal
                      - easyWon
                      - easyWinRounds
                      - mediumTotal
                      - mediumWon
                      - mediumWinRounds
                      - hardTotal
                      - hardWon
                      - hardWinRounds
                      - easyWinRate
                      - easyAvgRounds
                      - mediumWinRate
                      - mediumAvgRounds
                      - hardWinRate
                      - hardAvgRounds
                    nullable: true
                required:
                  - code
                  - status
                  - difficulty
                  - wins
                  - winRate
                  - avgRounds
                x-apifox-orders:
                  - code
                  - status
                  - difficulty
                  - wins
                  - winRate
                  - avgRounds
                  - myRank
                  - myProfile
              example:
                code: 200
                status: success
                difficulty: medium
                wins:
                  - rank: 1
                    user_id: 9XFNK2V3
                    username: user
                    ip_location: 内网/保留地址
                    value: 2
                    total_games: 30
                    won_games: 2
                    win_rate: 6.7
                    avg_rounds: 1
                win_rate:
                  - rank: 1
                    user_id: 9XFNK2V3
                    username: user
                    ip_location: 内网/保留地址
                    value: 6.7
                    total_games: 30
                    won_games: 2
                    win_rate: 6.7
                    avg_rounds: 1
                avg_rounds:
                  - rank: 1
                    user_id: 9XFNK2V3
                    username: user
                    ip_location: 内网/保留地址
                    value: 1
                    total_games: 30
                    won_games: 2
                    win_rate: 6.7
                    avg_rounds: 1
                my_rank:
                  wins: 1
                  win_rate: 1
                  avg_rounds: 1
                my_profile:
                  id: 3
                  user_id: 9XFNK2V3
                  username: user
                  cookie_token: LVoJxxEZVc2ujgJe93yMV3EtmoI5jmEiHTFIzzdj1mE
                  ip_location: 内网/保留地址
                  create_time: '2026-07-20T15:21:21'
                  update_time: '2026-07-20T15:35:02'
                  easy_total: 0
                  easy_won: 0
                  easy_win_rounds: 0
                  medium_total: 30
                  medium_won: 2
                  medium_win_rounds: 2
                  hard_total: 5
                  hard_won: 5
                  hard_win_rounds: 40
                  easy_win_rate: 0
                  easy_avg_rounds: 0
                  medium_win_rate: 0.06666666666666667
                  medium_avg_rounds: 1
                  hard_win_rate: 1
                  hard_avg_rounds: 8
          headers: {}
          x-apifox-name: 成功
        '400':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                    x-apifox-mock: '{{$number.int}}'
                  status:
                    type: string
                    x-apifox-mock: '{{$string.alpha}}'
                    title: 请求状态
                  message:
                    type: string
                    title: 详细信息
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              examples:
                '3':
                  summary: 传入数据校验失败
                  value:
                    code: 400
                    status: fali
                    message: 字"一"不在候选字中
                '4':
                  summary: 游戏不存在
                  value:
                    code: 400
                    status: fail
                    message: 游戏不存在
                '5':
                  summary: 游戏状态不符合要求
                  value:
                    code: 400
                    status: fail
                    message: 本局游戏已结束,状态不为playing
          headers: {}
          x-apifox-name: 请求内容未预期
        '401':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                    description: http标准响应代码
                    x-apifox-mock: '{{$number.int}}'
                  status:
                    type: string
                    title: 请求状态
                    x-apifox-mock: '{{$string.alpha}}'
                  message:
                    type: string
                    title: 详细信息
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              example:
                code: 401
                status: fail
                message: 缺少Authorization请求头
          headers: {}
          x-apifox-name: 未认证
        '403':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                    x-apifox-mock: '{{$number.int}}'
                  status:
                    type: string
                    title: 请求状态
                    x-apifox-mock: '{{$string.alpha}}'
                  message:
                    type: string
                    title: 详细信息
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              example:
                code: 403
                status: fail
                message: not admin
          headers: {}
          x-apifox-name: 无权限
        '405':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                  message:
                    type: string
                    title: 详细信息
                  status:
                    type: string
                    title: 请求状态
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              example:
                code: 405
                status: fail
                message: Method Not Allowed
          headers: {}
          x-apifox-name: 方法不许可
        '422':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                  status:
                    type: string
                    title: 请求状态
                  message:
                    type: string
                    title: 详细信息
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              example:
                code: 422
                status: fail
                message: guess 参数非法：Value error, 必须输入4字成语
          headers: {}
          x-apifox-name: 请求体有误
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                  status:
                    type: string
                    title: 请求状态
                  message:
                    type: string
                    title: 详细信息
                required:
                  - code
                  - status
                x-apifox-orders:
                  - code
                  - status
                  - message
              example:
                code: 500
                status: fail
                message: 服务器内部异常，请稍后重试
          headers: {}
          x-apifox-name: 内部错误
      security: []
      x-apifox-folder: api/leaderboard
      x-apifox-status: released
      x-run-in-apifox: https://app.apifox.com/web/project/8546191/apis/api-489663689-run
components:
  schemas: {}
  securitySchemes:
    普通token鉴权:
      type: bearer
      scheme: bearer
    管理员token验证:
      type: bearer
      scheme: bearer
servers:
  - url: http://127.0.0.1:8000
    description: 测试环境
security: []