openapi: 3.1.0
info:
  title: ChineseIdomWordle API
  version: 1.0.0
  description: 删除用户排行榜存档接口
paths:
  /api/leaderboard/profile/delete:
    post:
      summary: Api Delete My Profile
      description: 用户删除自己的存档
      operationId: api_delete_my_profile_api_leaderboard_profile_delete_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components: {}
